openapi: 3.0.3
info:
  title: Order Service
  description: Order Service
  version: 1.0.0
servers:
   - url: 'https://{hostname}/api'
     variables:
       hostname:
        default: 127.0.0.1
paths:
  /customer/{customerId}/orders/{orderId}:
    get:
      description: "Get Order"
      parameters:
        - in: path
          name: customerId
          schema:
            type: string
          required: true
        - in: path
          name: orderId
          schema:
            type: string
          required: true
      responses:
        '200':
          description: todo
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Order'
        default:
          description: todo
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'


  /customer/{customerId}/orders:
    post:
      description: "Create Order"
      parameters:
        - in: path
          name: customerId
          schema:
            type: string
          required: true
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateOrderRequest'
      responses:
        '200':
          description: todo
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Order'
        default:
          description: todo
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

components:
  schemas:
    Order:
      type: object
      properties:
        id:
          type: string
        customerId:
          type: string
        status:
          type: string
        items:
          type: array
          items:
            $ref: '#/components/schemas/Item'
        paymentLink:
          type: string

    Item:
      type: object
      properties:
        id:
          type: string
        name:
          type: string
        quantity:
          type: integer
          format: int32
        priceId:
          type: string
    Error:
      type: object
      properties:
       message:
         type: string

    CreateOrderRequest:
      required:
        - customerId
        - items
      type: object
      properties:
        customerId:
          type: string
        items:
          type: array
          items:
            $ref: '#/components/schemas/ItemWithQuantity'

    ItemWithQuantity:
      type: object
      properties:
        id:
          type: string
        quantity:
          type: integer
          format: int32